/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.AfiliadoData;
import entidades.Afiliado;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Monitor_Plano
 */
public class BusquedaApellidoForm extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla = new DefaultTableModel(){
            public boolean isCellEditable(int fila,int columna){
            return false;
        }
    };
    public BusquedaApellidoForm() {
        initComponents();
        cargarTablaApellido("ri");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaApellidos = new javax.swing.JTable();

        tablaApellidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaApellidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaApellidos;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaApellido(String _apellido) {

        AfiliadoData afi = new AfiliadoData();

        for (Afiliado afiliado : afi.buscarAfiliadoPorApellido(_apellido)) {
            Object[] fila = {
                
                afiliado.getIdAfiliado(),
                afiliado.getApellido(),
                afiliado.getNombre(),
                afiliado.getDni(),
                };
            modeloTabla.addRow(fila);
        }
    }

}
