/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import accesoADatos.AfiliadoData;
import accesoADatos.MetodoPago;
import accesoADatos.OrdenData;
import accesoADatos.PrestadorData;
import entidades.Afiliado;
import entidades.Orden;
import entidades.Prestador;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.Random;
import javax.swing.JInternalFrame;

/**
 *
 * @author 54266
 */
public class OrdenesForm extends javax.swing.JInternalFrame {

    private DefaultComboBoxModel<String> modeloCombo = new DefaultComboBoxModel<>();
    private boolean nuevo = true;

    private Afiliado _afiliado;
    private Prestador _prestador;
    private int _idCodigoOrden;

    public OrdenesForm() {
        initComponents();
        jbEliminar.setEnabled(false);
        jbGuardar.setEnabled(false);
        jbCancelar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtPago = new javax.swing.JTextField();
        jtAfiliado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtPrestador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbNuevo = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbBuscarAfiliado = new javax.swing.JButton();
        jCheckActivo = new javax.swing.JCheckBox();
        jbBuscarPrestador = new javax.swing.JButton();
        jdFecha = new com.toedter.calendar.JDateChooser();
        jcFormaPago = new javax.swing.JComboBox<>();
        jtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbBuscarOrden = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setText("Ordenes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Afiliado:");

        jtPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtAfiliado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prestador:");

        jtPrestador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Forma de Pago:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Activo:");

        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/agregar-archivo.png"))); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/eliminar.png"))); // NOI18N
        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Save_37110.png"))); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel_77947.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salida.png"))); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbBuscarAfiliado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbBuscarAfiliado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar.png"))); // NOI18N
        jbBuscarAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarAfiliadoActionPerformed(evt);
            }
        });

        jCheckActivo.setBackground(new java.awt.Color(102, 102, 102));
        jCheckActivo.setSelected(true);

        jbBuscarPrestador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbBuscarPrestador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar.png"))); // NOI18N
        jbBuscarPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarPrestadorActionPerformed(evt);
            }
        });

        jdFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jcFormaPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Importe:");

        jbBuscarOrden.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbBuscarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar.png"))); // NOI18N
        jbBuscarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtAfiliado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                        .addComponent(jtPrestador, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbBuscarOrden)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jbBuscarAfiliado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbBuscarPrestador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckActivo)
                            .addComponent(jcFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jbNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbBuscarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jbBuscarAfiliado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbBuscarPrestador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcFormaPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jCheckActivo))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jbEliminar)
                    .addComponent(jbGuardar)
                    .addComponent(jbCancelar)
                    .addComponent(jbSalir))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarAfiliadoActionPerformed
        // Método del boton buscar Afiliado por dni

        String _dni = JOptionPane.showInputDialog(null, "Ingrese el DNI del Afiliado");

        _afiliado = new Afiliado();
        _afiliado = (new AfiliadoData()).buscarAfiliadoPorDni(_dni);

        if (_afiliado != null) {

            jtAfiliado.setText(_afiliado.getApellido() + " " + _afiliado.getNombre());
            jbBuscarPrestador.requestFocus();
        } else {

            JOptionPane.showMessageDialog(null, "Debe dar de alta el afiliado.");
        }
    }//GEN-LAST:event_jbBuscarAfiliadoActionPerformed

    private void jbBuscarPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarPrestadorActionPerformed
        // Método del boton buscar prestador
        String _dni = JOptionPane.showInputDialog(null, "Ingrese el DNI del Prestador");
        _prestador = new Prestador();
        _prestador = (new PrestadorData()).buscarPrestadorPorDni(_dni);

        if (_prestador != null) {

            jtPrestador.setText(_prestador.getApellido() + " " + _prestador.getNombre());
            jdFecha.requestFocus();
        } else {

            JOptionPane.showMessageDialog(null, "Debe dar de alta el prestador.");
        }
    }//GEN-LAST:event_jbBuscarPrestadorActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // Método del boton salir
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // Método del boton Nuevo
        jcFormaPago.removeAll();
        LlenarCombo();
        limpiarControles();
        jbBuscarAfiliado.requestFocus();
        jbNuevo.setEnabled(false);
        jbGuardar.setEnabled(true);
        jbCancelar.setEnabled(true);
        nuevo = true;

        jlTitulo.setText(jlTitulo.getText() + " " + "(Creando orden)");
        Random random = new Random();
        jtCodigo.setText(Integer.toString(random.nextInt(90000) + 10000));

        String dia = ((jdFecha.getDate().toInstant().atZone(ZoneId.systemDefault())).toLocalDate()).getDayOfMonth() + "";
        String mes = ((jdFecha.getDate().toInstant().atZone(ZoneId.systemDefault())).toLocalDate()).getMonthValue() + "";
        jtCodigo.setText(dia + mes + "-" + jtCodigo.getText());

    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // Método del Boton Cancelar
        limpiarControles();
        jbNuevo.setEnabled(true);
        jbEliminar.setEnabled(false);
        jbGuardar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbNuevo.requestFocus();
        nuevo = true;

        jcFormaPago.removeAll();

        jlTitulo.setText("Ordenes");

        _afiliado = null;
        _prestador = null;
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // Método del boton guardar

        String _cliente = jtAfiliado.getText();
        String _medico = jtAfiliado.getText();
        String _pago = jtPago.getText();
        String _codigo = jtCodigo.getText();
        String _formPago = (String) jcFormaPago.getSelectedItem();

        if (_codigo.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Código no generado (crear una orden).");
            jbNuevo.requestFocus();
            return;
        }

        if (_afiliado == null && _cliente.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Debe Buscar un afiliado.");
            jbBuscarAfiliado.requestFocus();
            return;
        }

        if (_prestador == null && _medico.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Debe Buscar un prestador.");
            jbBuscarPrestador.requestFocus();
            return;
        }

        LocalDate hoy = LocalDate.now();
        LocalDate seleccionada = (jdFecha.getDate().toInstant().atZone(ZoneId.systemDefault())).toLocalDate();

        if (seleccionada.isBefore(hoy)) {
            JOptionPane.showMessageDialog(null, "No se puede sacar ordenes con fecha anterior al dia actual");
            jdFecha.requestFocus();
            return;
        }

        if (_pago.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Debe ingresar el monto a pagar.");
            jtPago.requestFocus();
            return;
        }

        if ((new OrdenData()).numerosOrdenesXafiliado(_afiliado.getIdAfiliado(), _prestador.getIdPrestador(), (jdFecha.getDate().toInstant().atZone(ZoneId.systemDefault())).toLocalDate())) {
            if (nuevo) {

                Orden _orden = new Orden(_codigo, _afiliado, _prestador, (jdFecha.getDate().toInstant().atZone(ZoneId.systemDefault())).toLocalDate(), _formPago, Double.parseDouble(_pago), true);
                (new OrdenData()).guardarOrden(_orden);
                _afiliado = null;
                _prestador = null;
                //java.awt.event.ActionEvent evt1 = null;
                jbCancelarActionPerformed(null);
            } else {

                Orden _orden = new Orden(_idCodigoOrden, _codigo, _afiliado, _prestador, (jdFecha.getDate().toInstant().atZone(ZoneId.systemDefault())).toLocalDate(), _formPago, Double.parseDouble(_pago), true);
                (new OrdenData()).modificarOrden(_orden);
                _afiliado = null;
                _prestador = null;
                jbCancelarActionPerformed(null);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Ya tiene una orden para el prestador para ese dia.");
        }


    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbBuscarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarOrdenActionPerformed
        // Método del boton buscar orden.
        String _codigo = jtCodigo.getText();

        if (_codigo.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Debe ingresar el código de la orden.");
            jtCodigo.requestFocus();
            return;
        }

        Orden _orden = new Orden();
        _orden = (new OrdenData()).buscarOrdenXcodigo(_codigo);

        _idCodigoOrden = _orden.getIdOrden();

        _afiliado = new Afiliado();
        _afiliado = _orden.getAfiliado();
        _prestador = new Prestador();
        _prestador = _orden.getPrestador();

        if (_orden != null) {

            LlenarCombo();
            jtCodigo.setText(_orden.getCodigo());
            jtAfiliado.setText(_afiliado.getApellido() + " " + _afiliado.getNombre());
            jtPrestador.setText(_prestador.getApellido() + " " + _prestador.getNombre());
            jdFecha.setDate(Date.valueOf(_orden.getFecha()));
            String _formaPago = _orden.getFormaPago();
            jcFormaPago.setSelectedItem(_formaPago);
            jtPago.setText(_orden.getImporte() + "");
            jCheckActivo.setSelected(_orden.isActivo());

            jbNuevo.setEnabled(false);
            jbEliminar.setEnabled(true);
            jbGuardar.setEnabled(true);
            jbCancelar.setEnabled(true);
            nuevo = false;
        }


    }//GEN-LAST:event_jbBuscarOrdenActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // Método del boton eliminar por id

        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Desea Eliminar los datos de la orden de Código " + jtCodigo.getText() + " ?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {

            (new OrdenData()).eliminarOrden(_idCodigoOrden);

        } else {
            // El usuario eligió no eliminar al alumno
        }

        limpiarControles();
        jbCancelarActionPerformed(null);
    }//GEN-LAST:event_jbEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckActivo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbBuscarAfiliado;
    private javax.swing.JButton jbBuscarOrden;
    private javax.swing.JButton jbBuscarPrestador;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcFormaPago;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtAfiliado;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtPago;
    private javax.swing.JTextField jtPrestador;
    // End of variables declaration//GEN-END:variables

    private void limpiarControles() {

        jtCodigo.setText("");
        jtAfiliado.setText("");
        jtPrestador.setText("");
        jdFecha.setDate(Date.valueOf(LocalDate.now()));
        jtPago.setText("");
        jCheckActivo.setSelected(true);
        jbNuevo.requestFocus();
    }

    private void LlenarCombo() {

        MetodoPago[] _metodosPago = MetodoPago.values();
        String[] nombreMetodo = new String[_metodosPago.length];

        for (int i = 0; i < _metodosPago.length; i++) {

            modeloCombo.addElement(_metodosPago[i].toString());
        }

        jcFormaPago.setModel(modeloCombo);
    }
}
